[book]
authors = ["Aayush Chalise"]
language = "en"
multilingual = false
src = "src"
title = "Linutil Docs"
description = "Linutil is a distro-agnostic toolbox designed to simplify everyday Linux tasks."

[output.html]
default-theme = "ayu"
preferred-dark-theme = "ayu"
smart-punctuation = true
mathjax-support = true
site-url = "/rustmdbook/"
git-repository-url = "https://github.com/harilvfs/rustmdBook/tree/main/src/"
edit-url-template = "https://github.com/harilvfs/rustmdBook/edit/main/{path}"

[output.html.playground]
editable = true
line-numbers = true

[output.html.code.hidelines]
python = "~"

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2

[output.html.redirect]
"/format/config.html" = "configuration/index.html"
